version: '3.1'

services:
  notebook:
    image: microns-phase3-nda-notebook:latest
    build:
      context: .
    env_file: .env
    volumes:
      - ${EXTERNAL_NOTEBOOKS}:/notebooks/workspace
    links:
      - database
    ports:
      - 8888:8888

  database:
    image: microns-phase3-nda-database:latest # This image should be first loaded from the downloaded tar file, reference SETUP.md for more information.
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=1073741824
    restart: always
    ports:
      - 3306:3306

  notebook-only:
    image: microns-phase3-nda-notebook:latest
    build:
      context: .
    env_file: .env
    volumes:
      - ${EXTERNAL_NOTEBOOKS}:/notebooks/workspace
    ports:
      - 8888:8888
